# Generated by Django 6.0.7 on 2026-07-28 08:05

import django.db.models.deletion
import django.utils.timezone
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام رابط اصلی')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_activity', models.CharField(max_length=255, verbose_name='حوزه فعالیت')),
                ('contact_person', models.CharField(max_length=255, verbose_name='شخص رابط')),
                ('job_title', models.CharField(max_length=255, verbose_name='سمت')),
                ('landline', models.CharField(max_length=20, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(max_length=20, verbose_name='تلفن همراه')),
                ('email_at_call', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('acquisition_source', models.CharField(max_length=255, verbose_name='نحوه آشنایی')),
                ('first_contact_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ اولین تماس')),
                ('result', models.CharField(max_length=255, verbose_name='نتیجه تماس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('follow_up_date', models.DateField(default=marketing.models.default_follow_up, verbose_name='تاریخ پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='marketing.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
