# Generated by Django 6.0.7 on 2026-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='first_contact_date',
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نحوه آشنایی'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='field_of_activity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حوزه فعالیت'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت'),
        ),
    ]
