# Generated by Django 6.0.7 on 2026-08-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_customer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='acquisition_source',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='email_at_call',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='field_of_activity',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='landline',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='website',
        ),
        migrations.AddField(
            model_name='customer',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نحوه آشنایی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='field_of_activity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حوزه فعالیت'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='customer',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='وبسایت'),
        ),
    ]
