# Generated by Django 6.0.7 on 2026-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_customer_full_name_alter_callrecord_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام رابط اصلی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
    ]
