# Generated by Django 6.0.7 on 2026-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_alter_customer_name_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام نام خانوادگی'),
        ),
    ]
