# Generated by Django 6.0.7 on 2026-09-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_remove_customer_name_alter_customer_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مشتری',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مشتریان',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='callrecord',
            name='duration_minutes',
            field=models.IntegerField(default=0, null=True, verbose_name='مدت زمان مکالمه (دقیقه)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
